github:
  sanbales: sanbales

channels:
  targets:
  - [sanbales, main]

travis:
  secure:
    BINSTAR_TOKEN: og7TMjaDWXOpLEDQNPXkFbCUa0emzgI9aqIOEaAXoB4pI7zeXvQIMEJ6FXdZsaOHmWu9Vh7E3fCA6PJ7xMcWgveneurx0dDQT+98lx6tX6hn8AIC5P2zhqw5ta0rYDOFw0Nu9rojgG6X2SRQjUpm0rS4W8CZ83ObQh2LRugX81SgEr2WPQx39z8kDCwSlErnP+XnHjSmD+F3f6c8QGMiMuBDYMQy/E/1W0vgVomAtyYkiSsgB2jbQrCuU8lhJMDfL409su2c77tpIj2fLJ8qh3vsDDDB2yhKWPM8/In+WzU6g6W+NMdKBdDsgK2SKPWwxkcIv7LkDg29rKzkWjwJ9fnWc64QiEG65vwLvtUn6VCLTsnM0tWNZiI2UuhRv3HGoPJWvXsb6TVayhelWW56ttepyoLJhslW/dhwgtLPO0rYQ9UsUxlkskTTetEtgmBWEZPr71B8b2LVyH2TcWAw/93QVO0iov8bC5sr8L49QOFb49W1yu6JjWVd19a1raYT/QEl5ynAd/0UdoiXDNIdiJ4tFnjb7g1zu5s6ofiKFq1PgBbhI8oUWfVvzis+solKWXktTWsORKe1KgCYiESWmZ5PpR7Yyo/Ukaejo7aB5RHkW/g2FfofS8F60Z1aC5HgfsOU6lzjxdref1LpB3pV4o2s1Ywxxo/i8w4v+wzYn2Y=
