github:
  sanbales: sanbales

channels:
  targets:
  - [sanbales, main]

travis:
  secure:
    BINSTAR_TOKEN: fqczYUTB29Rr0za7oejxThU2w+LrZgxxADLV69NuaqAyS8kc/OE7VuW/p3L0xk4SSquI7jNE777Ahe2XO4s724Imx8mJG/5fRAIVS/XAYwPMaMck+8I8vNP/gY6rJh8au5iiyftd21RBrexigfLSi/oiI7IVKr4baUdjraP5MZPe5ZgMBe+NFcAXR2Kx888YbTFLNCSsmk0FgnbVaHL3wZmRnU+dGv/9qBHdjFrCR3S55e/D7H6/H+M41ldogg6QiCDDgJ4C/WrrxXwqvQb9KHuEAb4BEtUS1vO03lSnnRay5GLX+RUdOgMllVlhvRiS9Xzh7v4sFaFLV1cC8JPaFyz8bAv4/ckvjseAuLeTwKjNTHJU3FgaDb/TKjLcGCjBX3MjPAHUb8wJX4ImFg0WK5Kd5Tg8TLU+kWa6YGU8kgZnUwy45BsOsb3qoHQaPgZbyt3dQOEowWRfQmaioa/Jm2NZ5rzdeR+JyBsifsGxLdYCSgc8zmRmlNkzrS+qFiWnm6Dq6v65/bi0I28gH8R5C9uKAbly43+tASsslWXoMv+iaT9JD0Rle/t7Nj2hPpG4l4HhXFe0ttIia8fd8rMsxEz2ogNphxVdaW2jUTWb4v3Kz2FzZjm3xun0QRQEfPJ3zOfGve+6WRJctAijLU98nGmPf9S/sLSDwb23qg6ki+4=
